import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const jsonPath = path.join(root, 'peds_drugs.json');
const htmlPath = path.join(root, 'index.html');
const checkOnly = process.argv.includes('--check');

const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const html = fs.readFileSync(htmlPath, 'utf8');
const replacement = `// DATA_START - generated by scripts/sync-data.mjs\nconst DRUG_DATA = ${JSON.stringify(data)};\n// DATA_END`;
const pattern = /\/\/ DATA_START - generated by scripts\/sync-data\.mjs\r?\nconst DRUG_DATA = .*?;\r?\n\/\/ DATA_END/s;

let next;
if (pattern.test(html)) {
  next = html.replace(pattern, replacement);
} else {
  const legacyPattern = /const DRUG_DATA = .*?;\r?\n\/\/ ={10,}\r?\n\/\/ STATE/s;
  if (!legacyPattern.test(html)) {
    throw new Error('index.html is missing DRUG_DATA and synchronization markers');
  }
  next = html.replace(legacyPattern, `${replacement}\n// ============================================================================\n// STATE`);
}
if (checkOnly) {
  if (next !== html) {
    console.error('Embedded DRUG_DATA is not synchronized with peds_drugs.json');
    process.exit(1);
  }
  console.log('Embedded DRUG_DATA matches peds_drugs.json');
} else {
  fs.writeFileSync(htmlPath, next, 'utf8');
  console.log('Updated index.html from peds_drugs.json');
}
